service: zap-bot-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'sa-east-1'}
  memorySize: 128
  timeout: 3

functions:
  send-message:
    handler: src/functions/finish-step/handler.finish_step
    events:
      - http:
          path: /finish-step
          method: post
          cors: true
  2fa-flow:
    handler: src/functions/2fa-flow/handler.start_2fa_flow
    events:
      - http:
          path: /2fa
          method: post
          cors: {
            origin: "*"
          }
  button-events:
    handler: src/functions/button-events/handler.button_events
    events:
      - http:
          path: /button_events
          method: post
          cors: {
            origin: "*"
          }        


plugins: 
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
          
